version: '3.7'

services:
  # MongoDB 服务（无密码，注意安全）
  oj-mongo:
    image: mongo:latest
    container_name: oj-mongo
    restart: always
    volumes:
      - ./data/mongo:/data/db
    ports:
      - "27017:27017"   # 方便本地访问（根据需要）

  # 后端服务
  oj-backend:
    build: ./backend
    container_name: oj-backend
    restart: always
    depends_on:
      - oj-mongo
    volumes:
      - ./data/file:/data/file
      - ./data/backend:/root/.hydro
    ports:
      - "80:8888"  # 映射外部80端口到容器8888端口

  # 判题服务
  oj-judge:
    build: ./judge
    container_name: oj-judge
    restart: always
    privileged: true
    depends_on:
      - oj-backend
    volumes:
      - ./data/judge:/root/.config/hydro
